### ISSUE TITLE
Merci --> Ok pour l'héberger ?

### ISSUE THREAD

**Issue by Scttpr** [nesk/covid-19-certificate#1]
Hello,

Merci pour ton petit formulaire bien sympa, c'est ok pour toi si je l'héberge ici pour mes proches ?

https://www.scttpr.com/covid-cert/

PS : Si tu veux que je diffuse plus, hésite pas !

Bonne soirée !

**Comment by nesk** [comment]
Pas de soucis tant que tu gardes les liens dans le footer ^^
