### ISSUE TITLE
Numeric attestations can no longer be stored on a mobile phone

### ISSUE THREAD

**Issue by Xwilarg** [nesk/covid-19-certificate#12]
Numeric attestations can no longer just be stored on mobile phone and must be printed.

The link given on "https://johann.pardanaud.com/covid-19-certificate/" (this one: https://twitter.com/design_gouv/status/1240177567434489856 ) no longer work

**Comment by nesk** [comment]
I've _just_ updated the app to reflect these changes :)  https://github.com/nesk/covid-19-certificate/commit/2f27c51a7047a6a4f51c55234f8a6193e7d46882
