### ISSUE TITLE
covid-19-certificate

### ISSUE THREAD

**Issue by NuggaN85** [nesk/covid-19-certificate#18]
Manque plus cas générer un code QR et le script est top

**Comment by nesk** [comment]
L'application officielle gère très bien ça. Mon générateur est encore en ligne uniquement pour ceux qui en ont encore l'usage pour imprimer. 😉

**Comment by NuggaN85** [comment]
> L'application officielle gère très bien ça. Mon générateur est encore en ligne uniquement pour ceux qui en ont encore l'usage pour imprimer. 😉

ok merci
