### ISSUE TITLE
Archivage du repo pour éviter les confusions

### ISSUE THREAD

**Issue by SasquatchYuja** [nesk/covid-19-certificate#19]
cf. https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/40#issuecomment-719651552

Je vous propose d'archiver ce repo pour éviter toute confusion future en ce qui concerne la version la plus à jour du générateur d'attestation.

**Comment by SasquatchYuja** [comment]
Au cas où l'historique est le suivant :
https://github.com/nesk/covid-19-certificate
puis
https://github.com/LAB-MI/deplacement-covid-19
puis
https://github.com/LAB-MI/attestation-couvre-feu-covid-19
puis
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020 (actuel)

**Comment by tomchen** [comment]
Ou bien mettez à jour ce repo en ajoutant le code QR et mettant à jour l'en-tête et les motifs.

A mon avis, bien que ce repo soit beaucoup plus simple (vanilla JS, même pas de npm, OMG, c'est rare aujourd'hui non? 😅), il est meilleur que LAB-MI/attestation-deplacement-derogatoire-q4-2020 en terme de la fonctionnalité. Je ne sais pas pourquoi l'application officielle de LAB-MI a été développée à partir de ce repo mais ils ont supprimé le champ de signature et l'enregistrement de profil, ce dernier est une chose essentielle (c'est sauvegardé localement, ça doit pas poser de problème en ce qui concerne la loi de cookie ou le RGPD ...)

**Comment by nesk** [comment]
Il existe déjà une note sur le site web qui indique que ce générateur n'est pas l'officiel. Je pense qu'un utilisateur perdu saura s'y retrouver en voyant ça.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/817508/98237276-f276e180-1f64-11eb-902e-7e050a19d765.png">

J'archiverai le repo un jour, mais pas tout de suite je pense.

>vanilla JS, même pas de npm, OMG, c'est rare aujourd'hui non? 😅

Fallait aller vite, le web sans complications c'est cool parfois ! 😛

**Comment by SasquatchYuja** [comment]
L'archivage c'est plus pour quelqu'un qui débarquerait sur ce repo et qui lirait mal le readme

**Comment by nesk** [comment]
Il y a un message dès le début du readme qui explique que le gouvernement a créé sa propre attestation, je pense que les gens sauront se repérer.

Archiver un repo ça amène plein de conséquences, dont je ne veux pas pour l’instant.
