### ISSUE TITLE
Display error when the city name is large

### ISSUE THREAD

**Issue by jualexandre** [nesk/covid-19-certificate#8]
<img width="599" alt="Capture d’écran 2020-03-18 à 10 12 55" src="https://user-images.githubusercontent.com/31278780/76944466-54fd6d80-6901-11ea-85a3-1a4404431e8e.png">

Thank you for your application :)

**Comment by Kocal** [comment]
Same issue with "Villefranche-sur-Saône"

**Comment by acolombier** [comment]
Just brought a PR in! Note that it will work with "Chateauneuf Sur Loire" but only with that case pattern, as full uppercase takes a wider space :)

All good with "Villefranche-sur-Saône" tho!

Just waiting for @nesk to review and merge, and you shall be ready to get sorted!

**Comment by nesk** [comment]
Fixed by #11.
